// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gexvlgjqlkozemxvornq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdleHZsZ2pxbGtvemVteHZvcm5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODMwMzAsImV4cCI6MjA2MzE1OTAzMH0.Z867TAhl1uBNDWUb-1gds7XtRd8a0LOvC26eG7ibWss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});